#version: '3.8'
#
#services:
#  # Eureka Server
#  eureka-server:
#    image: eureka-server:latest
#    build:
#      context: ./eureka-server  # Đường dẫn đến thư mục chứa mã nguồn Eureka Server
#    ports:
#      - "8761:8761"  # Cổng cho Eureka Server
#    networks:
#      - app-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker  # Đảm bảo Eureka Server sử dụng profile Docker nếu có
#
#  # API Gateway
#  api-gateway:
#    image: api-gateway:latest
#    build:
#      context: ./api-gateway  # Đường dẫn đến thư mục chứa mã nguồn API Gateway
#    ports:
#      - "8080:8080"  # Cổng cho API Gateway
#    depends_on:
#      - eureka-server
#      - product-service
#      - user-service
#    networks:
#      - app-network
#    environment:
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#      - SPRING_PROFILES_ACTIVE=docker
#
#  # Product Service
#  product-service:
#    image: product-service:latest
#    build:
#      context: ./product-service  # Đường dẫn đến thư mục chứa mã nguồn Product Service
#    ports:
#      - "8082:8082"  # Cổng cho Product Service
#    depends_on:
#      - eureka-server
#    networks:
#      - app-network
#    environment:
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#      - SPRING_PROFILES_ACTIVE=docker
#
#  # User Service
#  user-service:
#    image: user-service:latest
#    build:
#      context: ./user-service  # Đường dẫn đến thư mục chứa mã nguồn User Service
#    ports:
#      - "8081:8081"  # Cổng cho User Service
#    depends_on:
#      - eureka-server
#    networks:
#      - app-network
#    environment:
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#      - SPRING_PROFILES_ACTIVE=docker
#
#networks:
#  app-network:
#    driver: bridge  # Tạo một mạng cầu nối (bridge) giữa các dịch vụ
#

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "9093:9093"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - kafka-net
    ports:
      - "8070:8070"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - ./vault-config:/vault/config
      - ./vault-data:/vault/file
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - kafka-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9412:9411"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
