apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: assignment1-24module
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "product_service_24module"
  DB_USER: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka-service:9093"
  TEMPORAL_SERVER: "temporal-service:7233"
  ZIPKIN_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
