apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: assignment1-24module
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "user-service"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/user_service_24module"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: "kafka-service:9093"
        - name: DUBBO_REGISTRY_ADDRESS
          value: "zookeeper://zookeeper-service:2181"
        - name: SPRING_CLOUD_VAULT_URI
          value: "http://vault-service:8200"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: assignment1-24module
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 8081
  type: ClusterIP
